### ISSUE TITLE
Running the custom-project

### ISSUE THREAD

**Issue by javac9** [opencrx/opencrx-documentation#5]
Is there somewhere info on how to run the custom project once it's been assembled and imported into Eclipse?

**Comment by wfro64** [comment]
Google "eclipse add tomee server" and follow "http://tomee.apache.org/tomee-and-eclipse.html" in order to create a "Tomcat Server" in Eclipse. Find below a few screenshots. Make sure that you set the same options in "VM arguments" as in apache-tomee-plus-7.0.5/bin/setenv.sh or setenv.bat. Deploy the EAR from the custom project to the ./apps directory and launch Tomcat.

![ksnip_20200722-224129](https://user-images.githubusercontent.com/11387061/88228216-20167400-cc6f-11ea-9e5f-29fe63d9060b.png)
![ksnip_20200722-224232](https://user-images.githubusercontent.com/11387061/88228217-20af0a80-cc6f-11ea-8511-75a66a751434.png)
![ksnip_20200722-224319](https://user-images.githubusercontent.com/11387061/88228220-20af0a80-cc6f-11ea-9cd2-f1b04f576cc9.png)
![ksnip_20200722-224342](https://user-images.githubusercontent.com/11387061/88228221-2147a100-cc6f-11ea-9979-6bd68211ad05.png)
![ksnip_20200722-224535](https://user-images.githubusercontent.com/11387061/88228222-2147a100-cc6f-11ea-91e5-3766a3e7a93e.png)
![ksnip_20200722-224647](https://user-images.githubusercontent.com/11387061/88228224-21e03780-cc6f-11ea-8af7-038f9d1a3ed7.png)
![ksnip_20200722-225349](https://user-images.githubusercontent.com/11387061/88228227-21e03780-cc6f-11ea-8580-b7a119528987.png)

**Comment by javac9** [comment]
> Deploy the EAR from the custom project to the ./apps directory and launch Tomcat

1) Which `ear` from `/sample` are you referring to? I guess `sample-4.3.0.ear`?
2) I downloaded apache-tomee-plus-7.0.8 - it doesn't have the `/apps` directory but it does, like regular Tomcat, the `/webapps ` directory. To deploy it, I should then copy the above mentioned `ear` archive into the `webapps` and upon starting Tomcat, it should get unpacked, right?

Suppose the above steps worked, what's next? My guess is that by deploying manually the `ear` we're setting the server part up? Then how do we launch the `web` part?

**Comment by wfro64** [comment]
1. Install openCRX Server https://github.com/opencrx/opencrx-documentation/blob/master/Admin/InstallerServer.md. This gives you a working Tomcat environment
2. Deploy opencrx-core-CRX.ear located in ./opencrx-custom/jre-1.8/sample/deployment-unit/ to ./apps as described in https://github.com/opencrx/opencrx-documentation/blob/master/Sdk/CustomProject.md

**Comment by javac9** [comment]
I did so and there's been some progress. However, during the deployment, there's a couple of CRX-exceptions - is there a known cause to them?
`...
SCHWERWIEGEND: For security constraints with URL pattern [/jsp/*] only the HTTP methods [POST GET] are covered. All other methods are uncovered.
Jul 24, 2020 9:40:27 AM org.apache.tomcat.util.descriptor.web.SecurityConstraint findUncoveredHttpMethods
SCHWERWIEGEND: For security constraints with URL pattern [/wizards/*] only the HTTP methods [POST GET] are covered. All other methods are uncovered.

Fri Jul 24 09:40:30 CEST 2020: Base.register()
Fri Jul 24 09:40:30 CEST 2020: Sample.register()
Fri Jul 24 09:40:31 CEST 2020: Base.register()
Fri Jul 24 09:40:31 CEST 2020: Sample.register()

Jul 24, 2020 9:40:31 AM org.opencrx.kernel.layer.model.AccessControl_2$DefaultRealm getPrincipal
WARNUNG: null
org.openmdx.base.exception.ServiceException: org.openmdx.base.exception.ServiceException: **DefaultDomain.MEDIA_ACCESS_FAILURE**
    BasicException[0]
	Class = org.openmdx.base.dataprovider.layer.persistence.jdbc.Database_2
	Method = getPartialObject
	Line = 6819
	ExceptionClass = org.openmdx.base.exception.ServiceException
	ExceptionDomain = DefaultDomain
	ExceptionCode = MEDIA_ACCESS_FAILURE
	Timestamp = 2020-07-24T07:40:31.071Z
	Parameters:
	    0:	xri = xri://@openmdx*org.openmdx.security.realm1/provider/CRX/segment/Root/realm/Root/principal/admin-Root
	    1:	statement = SELECT  * FROM OOMSE2_PRINCIPAL v WHERE ((v.object_id LIKE ?) AND (v.object_id = ?))
	    2:	parameters = null
	    3:	sqlErrorCode = -5501
	    4:	sqlState = 42501
	StackTrace:
	    at org.openmdx.base.dataprovider.layer.persistence.jdbc.Database_2.getPartialObject(Database_2.java:6819)
	    at org.openmdx.base.dataprovider.layer.persistence.jdbc.Database_2.get(Database_2.java:6844)
	    at org.openmdx.base.dataprovider.layer.persistence.jdbc.RestInteraction.get(RestInteraction.java:166)
	    at org.openmdx.base.rest.spi.AbstractRestInteraction.handleQuery(AbstractRestInteraction.java:488)
	    at org.openmdx.base.rest.spi.AbstractRestInteraction.execute(AbstractRestInteraction.java:361)
	    at org.openmdx.base.resource.spi.AbstractInteraction.execute(AbstractInteraction.java:247)
	    at org.openmdx.base.rest.spi.AbstractRestInteraction.pass(AbstractRestInteraction.java:152)
....`

**Comment by wfro64** [comment]
Your stacktrace shows that your (HSQLDB) database is not up and running.

Maybe that helps https://stackoverflow.com/questions/12688068/how-to-read-and-understand-the-java-stack-trace

**Comment by javac9** [comment]
> Your stacktrace shows that your (HSQLDB) database is not up and running.
> 
> Maybe that helps https://stackoverflow.com/questions/12688068/how-to-read-and-understand-the-java-stack-trace

Thanks for the link. But isn't the HSQLDB supposed to start at the same time as the custom-project (as is the case with regular running of OpenCRX installation)? I just tried starting the db first (from the OpenCRX shortcut), then running the TomEE from Eclipse - didn't work, can't even reach login page this time.
